### ISSUE TITLE
Improve error handling and error messages

### ISSUE THREAD

**Issue by easoncxz** [easoncxz/homebrew-automation#7]
Bad example: https://travis-ci.org/easoncxz/hack-assembler/jobs/575310201

Very uninformative:

```
/Users/travis/.rvm/gems/ruby-2.4.2/gems/homebrew_automation-0.1.0/lib/homebrew_automation/bottle.rb:90:in `die': StandardError (StandardError)
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/homebrew_automation-0.1.0/lib/homebrew_automation/bottle.rb:34:in `build'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/homebrew_automation-0.1.0/lib/homebrew_automation/workflow.rb:32:in `block in build_and_upload_bottle'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/homebrew_automation-0.1.0/lib/homebrew_automation/tap.rb:47:in `chdir'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/homebrew_automation-0.1.0/lib/homebrew_automation/tap.rb:47:in `with_git_clone'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/homebrew_automation-0.1.0/lib/homebrew_automation/workflow.rb:24:in `build_and_upload_bottle'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/homebrew_automation-0.1.0/lib/homebrew_automation/cli/workflow_commands.rb:30:in `build_and_upload'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor.rb:238:in `block in subcommand'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/homebrew_automation-0.1.0/bin/homebrew_automation.rb:5:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/homebrew_automation.rb:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/homebrew_automation.rb:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
Script failed with status 1
```

**Comment by easoncxz** [comment]
Presumably fixed in 11a394c ; green on Travis: https://travis-ci.org/easoncxz/homebrew-automation/builds/602601529
