### ISSUE TITLE
Handle case when Formula to be built bottles for is already installed.

### ISSUE THREAD

**Issue by easoncxz** [easoncxz/homebrew-automation#8]
Currently we fail miserably in this case. I had to `brew uninstall` manually.

```
==> Installing hack-assembler from easoncxz/tmp-tap
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

Error: hack-assembler 0.1.1.26 is already installed
To upgrade to 0.1.1.27, run `brew upgrade hack-assembler`.
Traceback (most recent call last):
	18: from /Users/eason/.rbenv/versions/2.5.1/bin/homebrew_automation.rb:23:in `<main>'
	17: from /Users/eason/.rbenv/versions/2.5.1/bin/homebrew_automation.rb:23:in `load'
	16: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/homebrew_automation-0.1.3/bin/homebrew_automation.rb:5:in `<top (required)>'
	15: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	14: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	13: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	12: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	11: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	10: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	 9: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 8: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 7: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 6: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/homebrew_automation-0.1.3/lib/homebrew_automation/cli/workflow_commands.rb:32:in `build_and_upload'
	 5: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/homebrew_automation-0.1.3/lib/homebrew_automation/workflow.rb:24:in `build_and_upload_bottle'
	 4: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/homebrew_automation-0.1.3/lib/homebrew_automation/tap.rb:47:in `with_git_clone'
	 3: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/homebrew_automation-0.1.3/lib/homebrew_automation/tap.rb:47:in `chdir'
	 2: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/homebrew_automation-0.1.3/lib/homebrew_automation/workflow.rb:32:in `block in build_and_upload_bottle'
	 1: from /Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/homebrew_automation-0.1.3/lib/homebrew_automation/bottle.rb:39:in `build'
/Users/eason/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/homebrew_automation-0.1.3/lib/homebrew_automation/bottle.rb:99:in `die': StandardError (StandardError)
```

**Comment by easoncxz** [comment]
Previous commit broke the build (and didn't include tests…). Commit cdd8007 tries to fix these problems.
